import os
import sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from models.schema import JudgeSchema
from utils.llm_pick import pick_llm


llm_judge = pick_llm("medium", output_schema=JudgeSchema)

sql_query = "SELECT * FROM users;"

judge_prompt = f"""
You are an SQL Judge Agent. Your task is to determine whether a generated
SQL query is safe to execute based on the user's original query and the
provided database schema details.

The SQL query must not modify the database in any way. It should only
retrieve data.

You will be provided with:
1. The user's original query.
2. The database schema details, including schema names, table names,
   column names, data types, and sample data.
3. The SQL query generated by the SQL Analyst Agent.

Your responsibilities are:

- Determine whether the generated SQL query is safe to execute.
- Verify that the query only retrieves data.
- Verify that the query does not modify the database.
- Verify that the query is consistent with the user's original request.
- Verify that the query uses only tables and columns available in the
  provided database schema.
- Identify potentially dangerous SQL operations.
- Provide comments or feedback explaining why the query is safe or unsafe.

The following SQL operations must be considered UNSAFE:

- INSERT
- UPDATE
- DELETE
- DROP
- ALTER
- TRUNCATE
- CREATE
- GRANT
- REVOKE
- MERGE
- REPLACE
- EXEC
- CALL
- Stored procedure execution
- Database or schema modification
- Permission or privilege modification
- Any other operation that can modify database state.

The following operations are generally considered SAFE:

- SELECT
- WITH queries (CTEs) that ultimately perform only data retrieval.
- SELECT with JOINs.
- SELECT with WHERE, GROUP BY, HAVING, ORDER BY, and LIMIT.
- Aggregate functions such as COUNT, SUM, AVG, MIN, and MAX.
- Read-only database functions that do not modify database state.

Important security rules:

- Reject any query that can modify database data, schema, permissions,
  or database state.
- Reject queries containing multiple statements separated by semicolons
  if any statement is not strictly read-only.
- Do not assume that a query is safe merely because it starts with SELECT.
- Carefully inspect CTEs, subqueries, functions, and other SQL expressions
  for potentially modifying operations.
- Do not allow SQL injection or malicious SQL patterns.
- Do not execute the SQL query.
- Do not modify the database.
- Do not expose database credentials or internal system information.

You must return the result in the following format:

SAFE: YES
FEEDBACK: <brief explanation>

or

SAFE: NO
FEEDBACK: <brief explanation of the security issue>


Generated SQL Query:
{sql_query}

Determine whether the generated SQL query is safe to execute.
"""

response = llm_judge.invoke(judge_prompt).model_dump() 

print(response)
