from dataclasses import field
from operator import add
from typing import Annotated, Literal

from pydantic import BaseModel, Field

class AgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(
        default_factory=list,
        description="List of messages exchanged with the agent.",
    )
    user_question : str = Field(..., description="The original question asked by the user.")
    curated_ques : str = Field(..., description="Curated user questions for the agent.")
    prompt_query_context : str = Field(..., description="A detailed prompt with sql db context that will help ai agent to generate sql query.")
    is_safe : Literal["Yes", "No"] = Field(..., description="it indicates whether the generated SQL query is safe to execute or not.")
    comments : str = Field(..., description="Comments or feedback provided by the agent regarding the safety of the SQL query.")
    generated_sql_query : str = Field(..., description="The SQL query generated by the agent based on the provided context and user questions.")
    sql_query_execution_result : str = Field(..., description="The result of executing the generated SQL query.")
    final_answer : str = Field(..., description="The final answer provided by the agent after processing the SQL query execution result.")


class JudgeSchema(BaseModel):
    answer : Literal["Yes", "No"] = Field(..., description="it indicates whether the generated SQL query is safe to execute or not.")
    comments : str = Field(..., description="Comments or feedback provided by the judge regarding the safety of the SQL query.")



class ETLAgentSchema(BaseModel):
    messages : Annotated[list, add] = Field(..., description="List of messages to be processed by ETL agent")
    #user_question : str = Field(..., description="The original question asked by the user")

class RouterSchema(BaseModel):
    answer: Literal["sql", "etl"] = Field(..., description="indicate whether the user's question is related to sql or etl operations")
    comments: str= Field(..., description="addtional comment or feedback regarding the classification of the user question")

class DataAgentSchema(BaseModel):
    messages : Annotated[list, add] = Field(..., description="List of messages to be processed by the data data agent")
    route_response : str = Field(..., description="Response from the agent router indicating whether to route to sql or etl" )